theme: jekyll-theme-primer
title: Yelp Restaurant Recommendations
title: Collaborative Filtering
description: Recommendation
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
