theme: jekyll-theme-minimal
title: EDA
title: Baseline Model 1 (Arithmetic)
title: Baseline Model 2 (Ridge)
title: Collaborative filtering
title: Ensemble

description: Recommendation
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
