theme: jekyll-theme-minimal
title: collaborative-filtering
title: baseline-ridge-model

description: Recommendation
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
