theme: jekyll-theme-minimal
title: EDA
title: Baseline Model 1
title: Baseline Model 2
title: Collaborative filtering
title: Ensemble
description: Recommendation
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
