theme: jekyll-theme-minimal
title: Yelp Restaurant Recommendations

description: Recommendation
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
